import '../styles/globals.css'
import type { AppProps } from 'next/app'
import NavBar from 'components/nav'
import Head from 'next/head'
import { RecoilRoot } from 'recoil'

function MyApp({ Component, pageProps }: AppProps) {
	return (
		<>
			<Head>
				<title>Next Boiler Plate</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<NavBar />
			<RecoilRoot>
				<Component {...pageProps} />
			</RecoilRoot>
		</>
	)
}

export default MyApp
