import type { NextPage } from 'next'
import Head from 'next/head'

const test: NextPage = () => {
	return (
		<>
			<Head>
				<title>test 페이지</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
		</>
	)
}

export default test
